"""Upload a trained ATR router checkpoint to the Hugging Face Hub.

For maintainers. Use this once after training the distilled router:

    huggingface-cli login                  # one-time
    python -m atr.tools.upload_router \\
        --model_dir ./models/atr_router_distilbert \\
        --repo_id   <your-user>/atr-router-distilbert \\
        --private                           # optional, for staging

A minimal model card is generated if one is not already present at
`<model_dir>/README.md`.
"""
from __future__ import annotations

import argparse
from pathlib import Path


_MODEL_CARD_TEMPLATE = """\
---
license: mit
library_name: transformers
pipeline_tag: text-classification
tags:
  - distilbert
  - table-qa
  - hybrid-qa
  - agentic-rag
  - atr
base_model: distilbert-base-uncased
---

# ATR Distilled Router

DistilBERT 4-class classifier that selects one of the ATR execution primitives
(`TEXT` / `SQL` / `RETRIEVE` / `HYBRID`) for a given sub-query, conditioned on
sub-query features plus failed-route history.

Trained from oracle labels generated by an LLM-prompted teacher (§3.4 of the
paper). Inference is a single forward pass, with no per-sub-query LLM call.

## Usage

```python
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tok = AutoTokenizer.from_pretrained("REPO_ID_HERE")
mdl = AutoModelForSequenceClassification.from_pretrained("REPO_ID_HERE")
```

Or via the ATR CLI:

```bash
python -m atr.tools.download_router --repo_id REPO_ID_HERE --out_dir ./models/atr_router
python -m atr.online.main \\
    --router_type learned \\
    --router_model_path ./models/atr_router \\
    ...
```

## Labels

| id | label    |
|----|----------|
| 0  | TEXT     |
| 1  | SQL      |
| 2  | RETRIEVE |
| 3  | HYBRID   |

## Citation

See the ATR repository for the citation.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Upload ATR router to HF Hub.")
    parser.add_argument("--model_dir", required=True,
                        help="Local directory containing the trained DistilBERT.")
    parser.add_argument("--repo_id", required=True,
                        help="Target HF repo id, e.g. <user>/atr-router-distilbert.")
    parser.add_argument("--private", action="store_true",
                        help="Create as private (default: public).")
    parser.add_argument("--commit_message", default="Upload ATR router",
                        help="Commit message on the HF repo.")
    args = parser.parse_args()

    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError as exc:
        raise SystemExit(
            "huggingface_hub is required. Install with: pip install huggingface_hub"
        ) from exc

    model_dir = Path(args.model_dir).expanduser().resolve()
    if not model_dir.is_dir():
        raise SystemExit(f"--model_dir not found: {model_dir}")

    # Drop a default model card if missing.
    card_path = model_dir / "README.md"
    if not card_path.exists():
        card_path.write_text(
            _MODEL_CARD_TEMPLATE.replace("REPO_ID_HERE", args.repo_id),
            encoding="utf-8",
        )
        print(f"  wrote default model card → {card_path}")

    create_repo(args.repo_id, private=args.private, exist_ok=True)
    api = HfApi()
    api.upload_folder(
        folder_path=str(model_dir),
        repo_id=args.repo_id,
        commit_message=args.commit_message,
    )
    print(f"Uploaded {model_dir} → https://huggingface.co/{args.repo_id}")


if __name__ == "__main__":
    main()
